add_newline = false

format = '''
$directory$custom$git_branch$direnv
$character'''

[time]
format = ' [$time]($style)'
disabled = false

[custom.jj]
when = "jj root"
symbol = "󱗆 "
format = "[$symbol]($style)"
style = "fg:#7DCFFF"

[git_branch]
symbol = "󰊢 "
format = "[$symbol]($style)"
style = "fg:#E0AF68"

[character]
success_symbol = "[❯](bold fg:#9ECE6A)"
error_symbol = "[❯](bold fg:#F5758D)"
vimcmd_symbol = "[❮](bold fg:#9ECE6A)"

[direnv]
disabled = false
symbol = '󰌪 '
format = '[$loaded]($style) '
allowed_msg = ""
not_allowed_msg = ""
denied_msg = ""
loaded_msg = "󰌪 "
unloaded_msg = "󱋙 "
style = "fg:#8C73B9"

[directory]
read_only = " "
read_only_style = "fg:#F3748C"
style = "fg:#7AA2F7"
format = '[$path]($style) [$read_only]($read_only_style)'
